# Generated by the release workflow of https://github.com/x6c-co/age-plugin-rypt.
# Edits here are overwritten by the next release.
class AgePluginRypt < Formula
  desc "Plugin for age that wraps file keys with rypt.dev keys"
  homepage "https://github.com/x6c-co/age-plugin-rypt"
  license any_of: ["MIT", "Apache-2.0"]

  depends_on "age"

  on_macos do
    on_arm do
      url "https://github.com/x6c-co/age-plugin-rypt/releases/download/v0.1.0/age-plugin-rypt-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "b2a1c972beddf32c4429ccb6b73aad3177f3f1469708171b3e784f4363a1655d"
    end
    on_intel do
      url "https://github.com/x6c-co/age-plugin-rypt/releases/download/v0.1.0/age-plugin-rypt-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "b1cf3a0ec95c9597f1606215e0b0bec411a1d36c603b78de2006fe7901c97f1c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/x6c-co/age-plugin-rypt/releases/download/v0.1.0/age-plugin-rypt-v0.1.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "7aefd99b1c84001098dbe990be62aa365a4d6edc0ce964014ef8eacb45111dfd"
    end
    on_intel do
      url "https://github.com/x6c-co/age-plugin-rypt/releases/download/v0.1.0/age-plugin-rypt-v0.1.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "f8afeeff4304d9eb12b12711731fd1635c30f25a2a4138bc6a2550d41b0c5e61"
    end
  end

  def install
    bin.install "age-plugin-rypt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/age-plugin-rypt --version")
    identity = shell_output("#{bin}/age-plugin-rypt new --key 3f2a9c1e-7b4d-4e2a-9f10-6c8d5a2b1e47")
    assert_equal "age1rypt18u4fc8nmf48z48csdjx452c7gu9hx89g\n",
                 pipe_output("#{bin}/age-plugin-rypt recipient", identity)
  end
end
